FROM node:20-alpine AS build
WORKDIR /app

COPY frontend/mundial-frontend/package*.json ./
RUN npm ci --prefer-offline

COPY frontend/mundial-frontend/ .
RUN npm run build

FROM nginx:1.27-alpine AS runtime

RUN apk add --no-cache gettext

COPY --from=build /app/dist/mundial-frontend/browser /usr/share/nginx/html
COPY frontend/mundial-frontend/nginx.conf /etc/nginx/templates/nginx.conf.template
COPY frontend/mundial-frontend/entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

EXPOSE 80
ENTRYPOINT ["/entrypoint.sh"]
